version: '2'

volumes:
  blog-data:
    external: true
    driver: ${VOLUME_DRIVER}

services:
  blog-data:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ghost
      stdin_open: true
    volumes:
      - ${BLOG_DATA}:/var/lib/mysql
    tty: true
    labels:
      io.rancher.container.pull_image: always
      ident: 'true'

  blog:
    image: jamrizzi/ghost:latest
    environment:
      GHOST_URL: ${GHOST_URL}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    stdin_open: true
    tty: true
    links:
      - blog-data:mysql
    labels:
      io.rancher.container.pull_image: always

  ghost-proxy:
    image: jamrizzi/ghost-proxy:latest
    environment:
      GPROXY_GHOST: ${GHOST_URL}
      GPROXY_BLOG: ${BLOG_URL}
      GPROXY_USERNAME: ${GHOST_USERNAME}
      GPROXY_PASSWORD: ${GHOST_PASSWORD}
      GPROXY_CLIENT_SECRET: not_set_yet
      VIRTUAL_PORT: '3008'
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always

  public-website:
    image: groupthreads/public-website:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
